name: Build and deploy ASP.Net Core app to Azure Web App - GrannyEly
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'
      
      - name: Build with dotnet
        run: dotnet build ./GrannyEly.sln --configuration Release
      
      - name: dotnet publish
        run: dotnet publish ./GrannyEly.sln -c Release -o ./myapp
      
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ./myapp
          
  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_63A1F5B2FA6944D699862EA79CEB8616 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_5687987AF7164716BE668C171DE568ED }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_4A7D7192A89046428E48A1EEEFE9B167 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'GrannyEly'
          slot-name: 'Production'
          package: .
          
